Traceback (most recent call last):
  File "historical_analysis_event.py", line 31, in <module>
    weight1 = sys.argv[2]
IndexError: list index out of range
